#![no_std]

use crate::types::SemanticID;

// Compile-time map for core actions
// In a real implementation, this would be generated by `build.rs` from `ual.proto`

pub const ACTION_MOVE: SemanticID = 0x0A1;
pub const ACTION_SCAN: SemanticID = 0x0A2;
pub const ACTION_STOP: SemanticID = 0x0A0;

pub const ENTITY_DRONE: SemanticID = 0x0E1;
pub const ENTITY_BASE: SemanticID = 0x0E4;

pub fn get_name(id: SemanticID) -> Option<&'static str> {
    match id {
        ACTION_MOVE => Some("move"),
        ACTION_SCAN => Some("scan"),
        ACTION_STOP => Some("stop"),
        ENTITY_DRONE => Some("drone"),
        ENTITY_BASE => Some("base"),
        _ => None,
    }
}
