import os
import re
import sys
import logging

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), '../src'))
from ual.atlas import UniversalAtlas

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_api_docs(output_file="API_REFERENCE.md"):
    """
    自动生成 API 参考文档
    从代码和 Atlas 中提取信息。
    """
    logger.info("Generating API Reference...")
    
    atlas = UniversalAtlas()
    
    content = []
    content.append("# UAL API Reference & Semantic Registry")
    content.append("> Auto-generated by `doc_gen.py`. Do not edit manually.\n")
    
    # 1. Standard Semantic Registry
    content.append("## 1. Universal Atlas (Standard Registry)")
    content.append("Core semantic concepts mapped to standard Hex IDs.\n")
    content.append("| Hex ID | Concept | Category |")
    content.append("|--------|---------|----------|")
    
    # Sort IDs
    sorted_ids = sorted(atlas._id_to_concept.keys())
    
    for sid in sorted_ids:
        concept = atlas._id_to_concept[sid]
        # Determine category based on range
        category = "Unknown"
        if 0x0A0 <= sid < 0x0B0: category = "Action"
        elif 0x0B0 <= sid < 0x0C0: category = "Property"
        elif 0x0C0 <= sid < 0x0D0: category = "Logic"
        elif 0x0D0 <= sid < 0x0E0: category = "Modal"
        elif 0x0E0 <= sid < 0x0F0: category = "Entity"
        elif 0x0F0 <= sid < 0x100: category = "Meta-Cognition"
        
        content.append(f"| `0x{sid:03X}` | **{concept}** | {category} |")
        
    content.append("\n## 2. Industry Namespaces")
    for ns, mapping in atlas._namespaces.items():
        content.append(f"### Namespace: `{ns}`")
        content.append("| Hex ID | Concept |")
        content.append("|--------|---------|")
        for sid, concept in mapping.items():
             content.append(f"| `0x{sid:04X}` | {concept} |")
        content.append("")
             
    # Write to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(content))
        
    logger.info(f"Documentation written to {output_file}")

if __name__ == "__main__":
    generate_api_docs()
